# Generated by Django 3.2 on 2023-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default=3),
        ),
    ]
