# Generated by Django 3.2 on 2023-02-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_channels_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
