# Generated by Django 3.2 on 2023-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_subscription_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpamWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Спам слово',
                'verbose_name_plural': 'Спам слова',
            },
        ),
    ]
