# Generated by Django 3.2 on 2023-02-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230211_1543'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
