# Generated by Django 3.2 on 2023-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230221_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcategories',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'keyword')},
        ),
    ]
