# Generated by Django 3.2 on 2023-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230221_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
