# Generated by Django 3.2 on 2023-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20230222_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageid',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
